title: Colecionar Relógios
description: Relógios vintage e neo-vintage com curadoria, história e identidade.

url: "https://colecionarrelogios.com.br"

lang: pt-BR
timezone: America/Sao_Paulo

permalink: /:categories/:title/

paginate: 6
paginate_path: "/page:num/"

plugins:
  - jekyll-paginate

collections:
  posts:
    output: true

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      author: Colecionar Relógios

  - scope:
      path: ""
    values:
      layout: default
